### ISSUE TITLE
Have you met memory leak problem when running model？

### ISSUE THREAD

**Issue by Sucran** [Ugness/PiCANet-Implementation#9] opened 2018-10-08 11:36 UTC
Hi， @Ugness 
I met a RAM memory leak problem when running network.py and train.py， this issue confused me for a few days. I have run other pytorch repo which is OK. 
I run the code in Ubuntu 14.04, Pytorch 0.4.1, CUDA 8.0, cudnn 6.0.

**Comment by Ugness** [comment] 2018-10-08 14:36
Yes I also met memory leak problem.
In my case, my GPU's VRAM is 11 GB, and It spends about 9GB of VRAM for batch size 1.

**Comment by Sucran** [comment] 2018-10-08 16:05
Yes, I noticed the batch size option, it is wired and strange. I have no better idea so far, but I hope for further discussion. This week, I will go through the caffe code from author and see the difference in implementation in pytorch and caffe, going deeper in local PiCANet and global PiCANet.

**Comment by Ugness** [comment] 2018-10-08 23:39
Can you give me the link of caffe implementation? I didn't know that. Thanks.

**Comment by Ugness** [comment] 2018-10-09 00:46
Thanks a lot.

**Comment by Sucran** [comment] 2018-10-09 03:07
@Ugness I change the PiCANet config from ‘GGLLL’ to ‘GGGGG’ and ‘LLLLL’,  both of them have memory leak problem when running network.py,  have you met this before? I also found an interesting implementation of authors caffe code, they seem implemented an attpooling function on their own [proto](https://github.com/nian-liu/PiCANet/blob/master/caffe/src/caffe/proto/caffe.proto) [cpp](https://github.com/nian-liu/PiCANet/blob/master/caffe/src/caffe/layers/att_pooling_layer.cpp) which support their global or local attention function like conv3d. Can you give me a hint on how you thinking about the conv3d processing?

**Comment by Ugness** [comment] 2018-10-09 10:55
I think that would not work with 'GGGGG' or 'LLLLL'. I just tested with 'GGLLL' and other options may cause some tensor dimension error.

And I will check protocpp ASAP. for My conv3d processing, I will make some ppt slide or image to help your understanding. It is not easy to describe with text only. :(

**Comment by Ugness** [comment] 2018-10-09 11:29
# How Conv3d works?
## Assumption
* Lets say Image_batch's shape is (N x C x  H x W).  
and attention map( of each pixel position)'s shape is (h x w) (for global, h=H, w=W).
* We have (H * W) number of attention maps.  
Each attention map should be applied to each pixel's patch, every channel.
* I think to make this process with for loop takes a lot of time  
(I don't know how to use CUDA level for loop, and I heard that default for loop works on cpu),  
so I tried to use pytorch's pre-implemented Convolution functions.

## What's difference between convolution and 'PiCA' process?
* Convolution applies same kernel to each patch(pixel location), but different kernels to each channel, sample(batch_size).
* PiCA process applies same att_map to each channel, but different att_map to each patch(pixel location), sample(batch_size).  
  
## PiCA process with Conv3d
* On image side, my idea is send the dimension of batch and location to dim:1 (channel).  
(1, NxHxW, C, 13, 13)  --> for conventional conv3d, each dimension means (batch, channel, depth, H, W)
* On kernel side, my idea is each (1,1,7,7) kernel goes to (1,1,13,13) by using  
Then, Convolution function will apply same att_map to each channel, but diff att_map to each batch and location.
* But, location is 2D location but channel is 1D location. and also, we need to concern about N (batch_size) and make dilation as efficient as possible.  
So, it is not easy to use Conv2d.

**Comment by Ugness** [comment] 2018-10-09 12:07
X_X  
I thought Caffe is simillar to pytorch, but it wasn't.  
I tried to read the code, but I can't. The only thing I can see is they used for loop.  
If they used for loop for implementing PiCANet, for loop in python consumes a lot of time. without CUDA logic. And I don't know how to use CUDA for loop in python. T.T

**Comment by Ugness** [comment] 2018-10-10 13:05
Thanks. I also try to convert conv3d operation to combination of matrix multiplication.

**Comment by Ugness** [comment] 2018-10-14 07:58
@Sucran I think I can improve my model soon. There was no such function like torch.nn.Fold on pytorch 0.4.0 when I started this project. Now, I found the function that I need. Thanks.

**Comment by Ugness** [comment] 2018-10-14 12:38
Hi @Sucran  I made a new logic! 
You can check it on https://github.com/Ugness/PiCANet-Implementation/tree/Fold_Unfold
Now you can train my model with batch1, by using 3.5GB of VRAM.
I just started training code, so I'll report the training result about next week!

**Comment by Sucran** [comment] 2018-10-15 00:54
@Ugness Soooooo happy for it works! I check the branch of Fold_Unfold, the memory leak problem seems gone. The VRAM is also lower for increasing the batch size, but cannot be 10. I will check the channel setting of each layer by comparing the caffe version of the author, maybe there is something misunderstanding still exits.

**Comment by Ugness** [comment] 2018-10-15 01:30
@Sucran Thanks a lot for your interest. It gave a lot of improvement. It seems like training speed is also improved.
About the version of code, Fold_Unfold version is branch of origin (3*3 conv) not the Adjusted(1*1 conv) one.
I am training this code with 3*3 conv, batch_size 4.
I am going to close this Issue after report the result. If you find some errors or need help, please open another issue. :)

**Comment by Sucran** [comment] 2018-10-15 01:41
@Ugness Ok. Thanks for your work again. It is my pleasure.

**Comment by Sucran** [comment] 2018-10-19 03:06
@Ugness Anything new?

**Comment by Ugness** [comment] 2018-10-19 06:13
One of my model got about 88 on F-measure score with  200 samples of DUTS-TE which scored 87 with model in paper, So I think I need to measure score with all of DUTS-TE, on all of checkpoints. So it takes a little bit long time.

I ensure that new model(with bigger batch_size) performs much better. 
I think I can update repo on Sunday or next Monday.

**Comment by Ugness** [comment] 2018-10-21 06:02
I updated and merged branch.

**Comment by Ugness** [comment] 2018-10-22 04:13
No, it's adjusted one. I used (1*1 conv).
And It is same as author's version on paper. The curve is vaidation.

**Comment by Sucran** [comment] 2018-10-27 14:04
@Ugness Hi, I try to reproduce your result, but I am confusing how to compute the metric result you reported. I had a trained weight model, but which code file contains the test part code?

**Comment by Ugness** [comment] 2018-10-28 06:50
You can check the measuring code in pytorch/measure_test.py. It will report the result on tensorboard, and you can download csv from tensorboard.

**Comment by Sucran** [comment] 2018-10-30 01:49
Hi @Ugness, do you check your test code for computing Max F_b and MAE, I think there are problems here. 
1) The way of computing MAE which is different with MSE_Loss. It is torch.abs(y_pred - y).mean(). 
2) I do not familiar with scikit-learn, maybe the pr_curve computing is more efficient than handcraft one. but I got a different result of your code, I ref the code of  AceCoooool/DSS-pytorch, I think the problem can be here.

**Comment by Ugness** [comment] 2018-10-30 13:47
1. Ops. I found that MSE and MAE is not same. It's my mistake. I'll fix it.
2. I'll check how scipy measures F-beta score.
I used threshold to measure F-beta score, may be that was wrong.

http://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_recall_curve.html#sklearn.metrics.precision_recall_curve

For example, if threshold=0.7 and predicted value=0.8, I made 0.8 to 1. Like as making PR-curve.
And I plot Max-F score on all threshold space.
If I did not use threshold, maybe it scored 0.75 as like you get.
Thank you for your comment. I also think 0.877 is strange. Because my attention map was different from author's one.

**Comment by Sucran** [comment] 2018-10-31 09:17
@Ugness I do not think the scikit-learn API provided a correct way to compute max F-beta, but you can ref the paper "Salient Object Detection: A Survey" for Chapter 3.2. Usually, we have a fixed threshold which changes from 0 to 255, for binarizing the saliency map to compute precision and recall. F-beta is computed from the average precision and average recall of all images. Then we pick the maximum as max F-beta.

**Comment by Ugness** [comment] 2018-11-01 12:52
Thanks. I'll check the paper.

**Comment by Ugness** [comment] 2018-11-05 13:05
I found that my threshold is not same as Survey Chapter 4.2. I am going to re-measure the f score as soon as possible. Thanks.

**Comment by Ugness** [comment] 2018-11-06 14:05
I found that sklearn uses more specific threshold bins than 0 to 255. sklearn uses all possible values of each pixel as threshold.
So I used the evaluation code in DSS repo and fixed it little bit because it made NaN problem.
```
        for i in range(256):
            y_temp = (pred >= thlist[i]).float()
            tp = (y_temp * mask).sum()
            # avoid prec becomes 0
            prec[i], recall[i] = (tp + 1e-10) / (y_temp.sum() + 1e-10), (tp + 1e-10) / (mask.sum() + 1e-10)
        f_score = (1 + beta_square) * prec * recall / (beta_square * prec + recall)
        print(torch.max(f_score))
```
![image](https://user-images.githubusercontent.com/33034982/48068942-79c6d880-e217-11e8-9bca-e04d5681a844.png)
![image](https://user-images.githubusercontent.com/33034982/48068947-7df2f600-e217-11e8-9750-ad7fa2e113c9.png)

Upper one is sklearn, and below is DSS_repo's evaluation method.
I need to wait for a while to get a full result, but It seems there is no big diff between sklearn's one and DSS repo's one.

**Comment by Sucran** [comment] 2018-11-06 16:55
@Ugness Sorry, I found my test code had some mistake. I will report a new result these days of your model.

**Comment by Ugness** [comment] 2018-11-07 04:08
It's okay. Thanks.

**Comment by Sucran** [comment] 2018-11-08 07:52
I fix my test code，and I got the result of 36epo_383000step.ckpt on DUTS-TE
average mae: 0.0757, max fmeasure: 0.7803
if I use denseCRF，the result is
average mae: 0.0639, max fmeasure: 0.7886 on DUTS-TE
all test image resizes into 224*224 because of the dimension limit of attention module. 
Hope you can check the answer.

**Comment by Ugness** [comment] 2018-11-08 13:08
Can I get a code snippet from your test code? and also Can I get the threshold value when you get the max fmeasure score?

**Comment by Ugness** [comment] 2018-11-13 12:50
Hi, I uploaded result csv on https://drive.google.com/drive/u/0/folders/1A9qXGuvtqwSY0mEc5hbC-4b7ix8fLyfA

**Comment by Ugness** [comment] 2018-11-13 15:15
I think that F.interpolate() made the difference. I simply resize all image to 224*224 when I load data from the dataset without maintaining their aspect ratio.
If that resizing method is wrong, I think I need to train the model again with your resizing method. 
Please give me your comment.
Thanks.

**Comment by Ugness** [comment] 2018-11-14 05:05
Yes, I corrected MAE.
Oh, I check the difference on precision and recall now. Sorry. I'll test it again.

**Comment by Sucran** [comment] 2018-11-19 08:17
@Ugness Sorry, I was busy on my own thing these days. Have you test it again and determine which is the right answer?

**Comment by Ugness** [comment] 2018-11-19 12:19
Sorry. now I started to test my code. I'll report the result ASAP

**Comment by Ugness** [comment] 2018-11-19 12:54
scored 0.8546.
for MAE 0.05321

**Comment by Sucran** [comment] 2018-11-20 00:16
@Ugness It may be my mistake, could you tell me the model download link and the corresponding code of model definition?

**Comment by Ugness** [comment] 2018-11-20 01:29
And about your memory problem, how much VRAM and RAM do you have?
Where does the RAM problem occur? RAM or VRAM?

**Comment by Sucran** [comment] 2018-11-20 16:38
@Ugness I think the  F-score procedure code that you showed is correct. It is almost the same as I reported in 7 days ago, right? I just set the number of threshold as 100 and you set it as 256, which no cause too many differences, but the result still be 0.854 when you tested?  
The most strange thing hit on my mind is the difference of MAE results. I always got a value of 0.65 but you got 0.54, we test it with the same code. Oh man, it is wired!

**Comment by Ugness** [comment] 2018-11-21 04:41
I also think it is strange. And I have a few questions to compare our results.
1. Did you use all of DUTS-TE for testing?
2. How many images in your DUTS-TE folder? There was a few mismatching files which should be deleted in DUTS-TE.
3. Can you give me the threshold value which you used for the score 0.7803?
4. Did you explicitly round (convert to binary image) the mask images in DUTS-TE?
5. Did you use GPU for testing? (Did you use cuda mode with a single GPU?)

**Comment by Sucran** [comment] 2018-11-21 08:43
1. all DUTS-TE
2. I found this problem but these files do not cause a big difference.
3. Nope, I have no print this threshold. I will test it again.
4. Convert the mask images into range [0,1], this is done automatically.
5. Yes, single GPU for testing, cuda mode.

**Comment by Ugness** [comment] 2018-11-21 09:22
Thank you for answering.
for 3., If you want, can you test with my threshold option? I already have it. It is 0.6627.

**Comment by Sucran** [comment] 2018-11-23 06:52
@Ugness Sorry, the threshold I test is 0.8. I have no test your option yet, I need to wait for any available GPU in my lab.
I also have a problem, can you test the MAE result on all DUTS-TE without modifying the dataset? The difference of MAE result confused me.

**Comment by Ugness** [comment] 2018-11-24 17:50
What do you mean by without modifying the dataset?
I am going to upload all the result (MAE, F-measure, threshold) on google drive.
I also upload the list of image file names in my DUTS-TE Dataset with it.

**Comment by Sucran** [comment] 2018-11-28 02:33
@Ugness. I mean it should be 5019 images in DUTS-TE without deleting mismatching files, you should test on all 5019 images.

**Comment by Ugness** [comment] 2018-11-28 09:14
While DUTS-TE-Mask has 2 more images than DUTE-TE-Image?

**Comment by RaoHaobo** [comment] 2019-04-02 12:28
Hi,  @Ugness , I intergrate  your flie of measure.py and train.py ，but  I don't change the file of network.py . now , I set the value of batch_size is 2, at the first falling of learning rate,my  train loss can  falling .but after that,althought my learning rate falling ,my train loss never falling. And , I test my model on PASCAL-S ,the best value of MAE is 0.1243.could you help me and sovle this problem?

**Comment by Ugness** [comment] 2019-04-03 06:40
@RaoHaobo Can you give me some captures of your loss graph?? You may found it on Tensorboard.
And I think it is better to make new issue. Thanks.

**Comment by RaoHaobo** [comment] 2019-04-03 08:32
I change the learning rate decrease by per 15000, but  the case of  train loss never falling  is the same of your 7000. I  results  of  train loss and learning rate as follows.  Thanks!

![image](https://user-images.githubusercontent.com/44016031/55463979-b82cbc00-562c-11e9-8ae6-be70e8cf409e.png)

**Comment by Ugness** [comment] 2019-04-03 11:22
I think that graph looks fine. 

But if you think that loss should be more less, I recommend you to increase lr decay rate and lr decay step. The hyper parameters on my code, I just followed the implementation on PiCANet paper with DUTS Dataset. 
And about MAE, it may related to batch size. When I changed batchsize 1 to 10(may be 4 I do not remember correctly), the performance was incrementally increased. 

I’ll let you know the specific value of score when I found the past results.
And I’ll also upload the loss graph of my experiment as well. Thanks.

**Comment by RaoHaobo** [comment] 2019-04-04 07:31
I make the Ir decay rate  from 0.1 to 0.5，the Ir decay steps is 7000.And  my loss as follows
![image](https://user-images.githubusercontent.com/44016031/55537226-503eaa00-56ee-11e9-9b7e-4af09cf74b1a.png)
![image](https://user-images.githubusercontent.com/44016031/55537282-69dff180-56ee-11e9-8e39-62d6665f4593.png)

Why the train loss never falling after one opeoch？Do you meet the problem?

**Comment by Dylanqyuan** [comment] 2019-04-09 01:16
nice work and nice code!
When I run 'python train.py --dataset ./DUTS-TR',  there occurs a error:(it seems something wrong with tensorboardX, but i have no idea what to do):
![image](https://user-images.githubusercontent.com/37292157/55766644-21d31d00-5aa8-11e9-894a-2dd466add94b.png)
thanks for your reply~

**Comment by RaoHaobo** [comment] 2019-04-09 01:22
@Dylanqyuan  version of your tensorboardX is too high.

**Comment by Dylanqyuan** [comment] 2019-04-09 01:31
> @Dylanqyuan version of your tensorboardX is too high.

It works! Thank you buddy!

**Comment by Ugness** [comment] 2019-04-09 05:12
@RaoHaobo https://github.com/Ugness/PiCANet-Implementation/issues/16#issuecomment-479510008
I’ve uploaded my graph on that link. And I also suggest you to follow that links 3 steps to check if model is trained or not.

My graph is also fluctuating as like as yours, and looks it is not decreasing.
And for your graph, I am concerned about the learning rate. I think it became too small to train the model effectively after 1 epoch. But I did not had such experiment about that, so it’s just my personal opinion.

If you want to check your models performance, I suggest you to follow the steps on the link.
If you are worrying about non-decreasing training loss, I suggest you (and also I) to have more experiments with learning rate and the other hyperparameters.
In detail, 
- make lr decay rate between 0.9~1 or decay step much larger. 
- Please carefully observe that if the model is trained enoughly on that lr.
Thank you for your interest and I hope you to have much higher performance than my experiments! :)

**Comment by RaoHaobo** [comment] 2019-05-05 05:29
@Ugness  I test your the  '36epo_383000step.ckpt' on PASCAL-S ,and the result is  
![image](https://user-images.githubusercontent.com/44016031/57188894-32f13b80-6f39-11e9-9e3d-13e86a02c1d5.png)，but your result is 
![image](https://user-images.githubusercontent.com/44016031/57188896-4a302900-6f39-11e9-9aa1-4ce300dcad5f.png),
why? 
another problem:I add some my ideal on your code ,and I train my model is well:
![image](https://user-images.githubusercontent.com/44016031/57188907-82d00280-6f39-11e9-8afa-511555a9d867.png)
but when I test my model on your this code ：measure_test.py ,the test result is
![image](https://user-images.githubusercontent.com/44016031/57188919-c460ad80-6f39-11e9-92b9-98274f895eb5.png)

**Comment by RaoHaobo** [comment] 2019-05-05 08:41
@Ugness   the second problem have been solved ,the first isn't  sovled

**Comment by Ugness** [comment] 2019-05-07 09:11
If you got my result from the README.md, I trained and tested the model on ONLY DUTS Dataset. So the result on PASCAL-S dataset may differ.

**Comment by RaoHaobo** [comment] 2019-05-10 03:53
@Ugness  Ok，
![image](https://user-images.githubusercontent.com/44016031/57501356-d2d40e00-7319-11e9-9bd1-a093e1c81cd3.png)
this is your trained model ,and I use it to  test  on  PASCAL-S and SOD ,the max_F is 0.8379.Could you test your model on other dataset?

**Comment by RaoHaobo** [comment] 2019-05-13 12:33
@Ugness  this code  on  your measure_test.py .
![image](https://user-images.githubusercontent.com/44016031/57621348-cb349380-75bd-11e9-8d90-5ee8b02e9ef3.png)
but the github.com/AceCoooool/DSS-pytorch solver.py is 
![image](https://user-images.githubusercontent.com/44016031/57621421-f7501480-75bd-11e9-8a15-cb47bcb8bcdd.png) ,I think they have big different.

**Comment by Ugness** [comment] 2019-05-13 16:05
I've made that .sum(dim=-1) because my code evaluates several images on parallel.
The whole dimension of y_temp and mask is (batch, threshold_values, H, W).
If I execute .sum() like as below code, it would sum all values in y_temp. Although we should sum only on H and W axis.
And for the 1e-10, I made them for avoiding division by zero problem.
If you think my explanation is wrong, please give me your advice. Thanks.

**Comment by RaoHaobo** [comment] 2019-05-14 00:52
i mean that tp + 1e-10,the 1e-10 maybe take out ,I try to take out it ,but the max_F falling much.
 I also use the Dss code to test your model on DUTS-TE,the result is bad.

**Comment by RaoHaobo** [comment] 2019-05-14 00:53
@Ugness  i mean that tp + 1e-10,the 1e-10 maybe take out ,I try to take out it ,but the max_F falling much.
I also use the Dss code to test your model on DUTS-TE,the result is bad.

**Comment by Ugness** [comment] 2019-05-16 07:58
How much difference that follows from the error?
Is the difference significant?
Let me know it. Thanks.

**Comment by RaoHaobo** [comment] 2019-05-16 08:03
when threhold equal to 1,the prec must be 0,but your result equal to 1

**Comment by RaoHaobo** [comment] 2019-07-31 03:35
@Ugness 
      The writer.add_pr_curve()  function in  measure.py  can't work ,  It never show in the  tensorboard . I think it caused by the version tensorboard. 
![c58dafe5b088c12bd987229dc5cb70f](https://user-images.githubusercontent.com/44016031/62181858-41f45800-b387-11e9-8338-f1a47f6c7397.png)

**Comment by Ugness** [comment] 2019-08-01 09:59
https://github.com/tensorflow/tensorboard/releases 
Would you try it with the tensorboard 1.8.0???

**Closed** 2020-07-22 11:35 UTC
